--queue some expeditions
-- select create_expedition(2,'Beta');
-- select create_expedition(2,'Sigma');
-- select create_expedition(2,'Tau');
-- select create_expedition(3,'Tau');
-- select create_expedition(2,'Beta');
-- select create_expedition(2,'Beta');
-- select create_expedition(2,'Beta');
-- select create_expedition(2,'Beta');
select create_expedition(2,'Beta');
-- update moon set dangerlevel=50 where name='Beta';