DROP VIEW IF EXISTS EMPLOYEE_STATUS;
CREATE VIEW EMPLOYEE_STATUS AS
    SELECT DISTINCT E.ID AS EMPLOYEE_ID, 
            E.NAME, 
            E.SURNAME, 
            E.RANK, 
            E.HEARTRATE, 
            E.HEALTH,
            E.SHIPID AS SHIP, 
            COALESCE(
                EXP.MOONNAME,
                'IDLE'
            ) AS EXPEDITION_TARGET,
            FORMAT('%s, %s, %s', S.COORDX, S.COORDY, S.COORDZ) AS LOCATION

    FROM EMPLOYEE E
    LEFT JOIN (
        SELECT EXP.*
        FROM EXPEDITION EXP
        WHERE EXP.DATEOFDEPARTURE IS NOT NULL
        AND EXP.DATEOFRETURN IS NULL
    ) EXP ON EXP.SHIPID = E.SHIPID
    LEFT JOIN SHIP S ON S.ID = E.SHIPID
    ORDER BY
        E.ID;