DROP VIEW IF EXISTS EMPLOYEE_STATUS;
CREATE VIEW EMPLOYEE_STATUS AS
    SELECT  E.ID AS EMPLOYEE_ID, 
            E.NAME, 
            E.SURNAME, 
            E.RANK, 
            E.HEARTRATE, 
            E.SHIPID AS SHIP, 
            COALESCE(
                EXP.MOONNAME,
                'IDLE'
            ) AS EXPEDITION_TARGET,
            FORMAT('%s, %s, %s', S.COORDX, S.COORDY, S.COORDZ) AS LOCATION

    FROM EMPLOYEE E
    LEFT JOIN EXPEDITION EXP ON E.SHIPID = EXP.SHIPID
    LEFT JOIN SHIP S ON S.ID = E.SHIPID
    WHERE EXP.DATEOFRETURN IS NULL
    ORDER BY
        E.ID;