DROP VIEW IF EXISTS SHIP_STATUS;
CREATE VIEW SHIP_STATUS AS
    SELECT S.ID AS SHIP_ID,
            COUNT(DISTINCT EMP.ID) AS PEOPLE_ON_DECK,
            COALESCE(SUM(DISTINCT SC.VALUE), 0.00) AS VALUE_ON_DECK,
            S.MAXLOAD - S.LOAD AS LOAD_LEFT,
            S.MAXVOLUME - S.VOLUME AS VOLUME_LEFT,
            ROUND((S.FUEL / S.MAXFUEL)::numeric, 2) AS FUEL_PERCENTAGE,
            COALESCE(COUNT(DISTINCT ENG_WORKING.ID), 0) AS ENGINES_RUNNING,
            ROUND((SUM(DISTINCT E.POWER)/COUNT(DISTINCT E.ID))::numeric, 2) AS SHIP_POWER,
            FORMAT('%s, %s, %s', S.COORDX, S.COORDY, S.COORDZ) AS LOCATION,
            COALESCE(
                EXP.MOONNAME,
                'IDLE'
            ) AS EXPEDITION_TARGET

    FROM SHIP S
    LEFT JOIN SHIP_ENGINE E ON S.ID = E.SHIPID
    LEFT JOIN (
        SELECT SE.ID, SE.SHIPID AS WE_SHIPID
        FROM SHIP_ENGINE SE
        WHERE STATE = 'Working'
    ) ENG_WORKING ON S.ID = WE_SHIPID
    LEFT JOIN (
        SELECT EXP.*
        FROM EXPEDITION EXP
        WHERE EXP.DATEOFRETURN IS NULL
        AND EXP.DATEOFDEPARTURE IS NOT NULL
    ) EXP ON S.ID = EXP.SHIPID
    LEFT JOIN EMPLOYEE EMP ON S.ID = EMP.SHIPID
    LEFT JOIN SCRAP SC ON S.ID = SC.SHIPID
    GROUP BY
        S.ID, EXP.MOONNAME
    ORDER BY
        S.ID;