DROP VIEW IF EXISTS SHIP_PARAMS;
CREATE VIEW SHIP_PARAMS AS
    SELECT 
        S.ID AS SHIP_ID,
        S.MAXFUEL AS TANK_CAPACITY,
        S.MAXLOAD AS CARGO_WEIGHT_CAPACITY,
        S.MAXVOLUME AS CARGO_VOLUME_CAPACITY,
        COALESCE(COUNT(DISTINCT E.ID), 0) AS ENGINE_COUNT
    FROM SHIP S
    LEFT JOIN SHIP_ENGINE E ON E.SHIPID = S.ID
    GROUP BY S.ID
    ORDER BY S.ID;