DROP VIEW IF EXISTS EXPEDITION_STATUS;
CREATE VIEW EXPEDITION_STATUS AS
    SELECT DISTINCT EXP.ID AS EXPEDITION_ID,
            EXP.DATEOFDEPARTURE as DATE_OF_DEPARTURE,
            EXP.DATEOFRETURN AS DATE_OF_RETURN,
            COALESCE(EXP.TOTALSCRAP, 0.00) AS TOTAL_SCRAP,
            EXP.SHIPID AS SHIP_ID,
            EXP.MOONNAME AS TARGET_MOON,
            CASE
                WHEN EXP.DATEOFDEPARTURE IS NULL THEN 'PENDING'
                WHEN EXP.DATEOFRETURN IS NULL THEN 
                    CASE 
                        WHEN EMP_LIVE_COUNT = 0 OR EMP_LIVE_COUNT IS NULL THEN 'WIPED'
                        WHEN (SHP.COORDX <> MN.COORDX OR SHP.COORDY <> MN.COORDY OR SHP.COORDZ <> MN.COORDZ) THEN 'FLYING'
                        ELSE 'IN PROGRESS'
                    END
                ELSE 'FINISHED'
            END AS EXPEDITION_STATUS
    FROM EXPEDITION EXP
    LEFT JOIN SHIP SHP ON EXP.SHIPID = SHP.ID
    LEFT JOIN MOON MN ON MN.NAME = EXP.MOONNAME
    LEFT JOIN (
        SELECT SHIPID, COUNT(ID) AS EMP_LIVE_COUNT
        FROM EMPLOYEE
        WHERE HEARTRATE <> 0
        GROUP BY SHIPID
    ) EMP_LIVE ON EMP_LIVE.SHIPID = EXP.SHIPID
    ORDER BY
        EXP.ID;
