DROP VIEW IF EXISTS EMP_EXP_STATUS;
CREATE VIEW EMP_EXP_STATUS AS
    SELECT 
    EMP.ID AS employee_id,
    EMP.RANK AS RANK,
    EMP.SURNAME AS SURNAME,
    EMP.NAME AS NAME,
    EMP.HEARTRATE AS HEARTRATE,
    COALESCE(SUM(SC.VALUE),0.00) AS COLLECTED_VALUE,
    EXP.MOONNAME AS TARGET_MOON
FROM EMPLOYEE EMP
INNER JOIN EXPEDITION EXP ON EXP.SHIPID = EMP.SHIPID
LEFT JOIN SCRAP SC ON EMP.ID = SC.EMPLOYEEID
WHERE DATEOFRETURN IS NULL
GROUP BY EMP.ID, EXP.ID
ORDER BY EMP.ID;