DROP VIEW IF EXISTS EMP_EXP_STATUS;
CREATE VIEW EMP_EXP_STATUS AS
    SELECT 
    EXP.ID AS EXPEDITION_ID,
    EMP.ID AS employee_id,
    EMP.RANK AS RANK,
    EMP.SURNAME AS SURNAME,
    EMP.NAME AS NAME,
    EMP.HEARTRATE AS HEARTRATE,
    EMP.HEALTH AS HEALTH,
    COALESCE((SELECT SUM(SC.VALUE)
                FROM SCRAP SC 
                WHERE SC.EXPEDITIONID = EXP.ID 
                AND SC.EMPLOYEEID = EMP.ID),0.00) AS COLLECTED_VALUE,
    EXP.MOONNAME AS TARGET_MOON
FROM EMPLOYEE EMP
INNER JOIN EXPEDITION EXP ON EXP.SHIPID = EMP.SHIPID
WHERE EXP.DATEOFRETURN IS NULL
AND EXP.DATEOFDEPARTURE IS NOT NULL
ORDER BY EMP.ID;